Update blogs-original.csv
shidenggui/bloghub pull request #187
Opened 2022-04-05 14:05 UTC by Thoxvi

Add [Huiliu](https://fucktheworld.top)

2022-04-07 13:42 UTC, kang8 requested changes
博客非常不错，但新的博客应该加在最后一行。

2022-04-07 14:00 UTC, Thoxvi commented
> 博客非常不错，但新的博客应该加在最后一行。

行，还有其他排序依据吗？

2022-04-08 01:16 UTC, kang8 commented
> 行，还有其他排序依据吗？

👍 , 没有其他排序规则了。不过如果能将两个 commit squash 成一个就更好了。

另外提一句，本仓库已经有半年的时间没有人维护了，所以建议给另外一个活跃的 repo https://github.com/timqian/chinese-independent-blogs 提交 PR。

2022-04-08 02:58 UTC, Thoxvi commented
> > 行，还有其他排序依据吗？
> 
> +1 , 没有其他排序规则了。不过如果能将两个 commit squash 成一个就更好了。
> 
> 另外提一句，本仓库已经有半年的时间没有人维护了，所以建议给另外一个活跃的 repo https://github.com/timqian/chinese-independent-blogs 提交 PR。

那个仓库我已经提过了。既然这个仓库已经不再维护，那么我就关闭这个 PR 了

2022-04-08 02:58 UTC, closed without merging